### ISSUE TITLE
Does this project still work

### ISSUE THREAD

**Issue by bradserbu** [truthy/botornot-python#6]
After properly configuring the application, I'm getting no output from the python program.

Also, hitting the REST endpoint returns a 500.

**Comment by clayadavis** [comment]
Yes, this project still works. I apologize that the error messages from the API backend aren't very informative, that's definitely a spot where we need more work (see the other two open issues).

As far as your particular issue goes, could you start by giving me the following:
* Which version of botornot-python are you using (i.e. how did you install it, via git or pip?)
* What OS and Python version are you using?
* What sequence of commands did you run?

**Comment by bradserbu** [comment]
- I'm using `botornot-0.1`.  I've tried installing via `pip`, and via `setup.py`.
- I'm using OSX and Python 2.7.12
- I typed in the program mentioned in the readme, and supplied my credentials
- No, when I hit the rest endpoint directly, I only included the recent posts for the user from their timeline.

**Comment by clayadavis** [comment]
No problem @bradserbu , I appreciate you letting me know with a GH issue. I haven't been able to test much on OSX, but everything seems to be working on my 2.7.11. I'll try to test on OSX later today.

Re: the API endpoint, the data has to be supplied in a particular way. See the [HTTP API](http://truthy.indiana.edu/botornot/http-api.html#Step-2:-Submit-data-to-BotOrNot) section on this.

Finally, I just pushed version 0.2. I don't think I changed anything that will affect this issue, but just in case, go ahead and get the new version and try it out.

**Comment by clayadavis** [comment]
I tested with Python 2.7.12 on OSX and everything worked for me. Which REPL are you using? Is it just a printing issue? Just to rule everything out, what happens when you do the following?
```python
result = bon.check_account('@clayadavis')
print(type(result), result)
```

**Comment by bradserbu** [comment]
Okay.  That makes me feel a little dumb.  It worked and I see the results.

I wanted to run the python program to trace the HTTP output to see what is different between the JSON content from the HTTP Post requests I made that were failing with an unknown error.

I suggest you make a small update to the HTTP documentation to include the format of the "content" variable.  I'd be happy to do this if it were a wiki format.

**Comment by clayadavis** [comment]
@bradserbu I think that's a very good idea. Issue #5 is to create a troubleshooting/FAQ guide, and I hadn't thought of using a wiki for that. I just made a [stub in the wiki](https://github.com/truthy/botornot-python/Troubleshooting-&-FAQ) and I'd love it if you could add that piece. However I must confess that I don't know the best way for people to contribute to a GH wiki; can one do a pull request?

Finally, could you share the exact JSON schema of the HTTP API request you tried to make? I want to update the API backend to check the schema and give a more informative error message when it doesn't match, and I'd like to use your (failed) request to test it.

**Comment by bradserbu** [comment]
@clayadavis Sorry for the late reply.

Here is a GIST with the payload I sent via POST:
https://gist.github.com/bradserbu/37ea9a17e0c1fce3e19f5d072deec063

Basically, the `content` parameter is a JSON array of my most recent posts from the `user_timeline` endpoint.

I was not able to access that Wiki link above.

**Comment by clayadavis** [comment]
@bradserbu thanks for the Gist. [Here is the correct link](https://github.com/truthy/botornot-python/wiki/Troubleshooting-&-FAQ) to the wiki stub.
