### ISSUE TITLE
BotOrNot object doesn't have attribute 'check_accounts_in'

### ISSUE THREAD

**Issue by tofunth** [truthy/botornot-python#7]
Dear botornot's authors,

I am sorry if my issue is too basic.

I tried to follow the quick guide to check a list of 180 twitter user accounts in Python. I got the message 
`AttributeError: 'BotOrNot' object has no attribute 'check_accounts_in'`

I then switched to use 'check_account' using list comprehension, but when the list had more than 1 user, it gave the error
`tweepy.error.TweepError: Not authorized.` 

I installed botornot from pip and its version is 0.2.

Thanks,
Hieu

**Comment by tofunth** [comment]
Actually some users gave the exception `tweepy.error.TweepError: Not authorized.`, not becase the list is more than one. I can use 'check_account' with a for loop at the moment.

Hieu

**Comment by clayadavis** [comment]
The version on pip is 0.2 where the version here is 0.3-alpha. Do you know how to install from Git? Could you help test the `check_accounts_in` method?

**Comment by tofunth** [comment]
I installed botornot-0.3a0 from the git repo and the method `check_accounts_in` worked fine. Thank you for the help!

**Comment by clayadavis** [comment]
@tofunth FYI I released 0.3 on PyPI today, so it should be pip installable.
